### ISSUE TITLE
strings click issue

### ISSUE THREAD

**Issue by fractalgee** [codygeary/CVfunk-Modules#3]
I just pulled the latest nightly and fired up Strings (cool module but currently not usable due to all knobs causing clicks), anything plugged into any of the inputs apart from the env inputs (chord into Chord bank 1 input for example) cause clicks. Also apart from the clicks the volume is rather low, maybe due to strummer actually outputting triggers, so there some more experimentation is needed, though hopefully that could work, as it's the only module I know of that can imitate strumming across the 6 strings.

I hooked up the Nysthi Strummer module to strum the 6 strings, with a trigger into the first of the bank of 6 strummer outs. That works fine until i move any of the knobs or the chord into Chord Bank 1 or Chord 1  inputs changes chord, click again. Sure that is not intended, but thought I'd drop you a note so that perhaps this can be fixed before Library team gets to building these. 

I am running an M1 Mini with MacOS 14.4, Rack Pro 2.4.1 arm64 (standalone).

**Comment by codygeary** [comment]
Ah, that's because the module isn't an oscillator.  It only generates v/oct CVs and gates of the muted channels.  The env inputs are to pitch bend the output CVs, so they work like an FM input.

You need to plug the output TRIG into the IMPULSE CONTROLLER to make the strumming envelopes, and then strum a module like the Pluck.

The manual.pdf has some patch examples, but I should probably make a demo patch for this one, as it's not super straightforward to patch.

**Comment by codygeary** [comment]
<img width="910" alt="image" src="https://github.com/codygeary/CVfunk-Modules/assets/4908063/4b3e4612-befa-4c74-879f-e07f3d3e16ff">

**Comment by fractalgee** [comment]
aha, my bad, sorry for the noise. Makes sense but still a bit cumbersome to patch up but will give it a go.

**Comment by codygeary** [comment]
No problem! :-)  I was originally planning on making it into an oscillator, but it became clear after a bit of development that the module was quite complex already.

I had to use 6 Pluck modules for the demo patch, since even though they are technically polyphonic modules, the poly copies all use the same mono trigger. So if you want to strum the strings separately you've gotta have duplicates.

It also works nice if you patch all the v/oct outs to a regular oscillator like VCV VCO, the TRIG to the sync input, and then through a MUTE8 to your VCA (patch the MUTES out to the MUTE8 to turn off the muted strings). This works nice in poly as well, with IMPULSE CONTROLLER to make the plucks and ENVELOPE ARRAY to make the envelopes (you can right-click on the envelope module to change the retriggering behavior) .

**Comment by fractalgee** [comment]
Hi @codygeary 
I have patched Strings up as per your image but without the mutes and get on many chords that out1 goes to -10V and stutters (makes a low grouwling sort of noise for ages before it fades down, unless a new chord comes in to land on a row/column where none of the outs go into that weird mode. No idea how to stop that. If I unpatch out 1 and only use the other 5 outs it's mostly OK, but now and then another out goes to -10 and makes that weird noise. Am I still doing something wrong or is this a bug?

Here is the patch (delete the .zip suffix, as this is only way to get a patch uploaded to git) :

[StringsOut1Mad.vcv.zip](https://github.com/codygeary/CVfunk-Modules/files/14745612/StringsOut1Mad.vcv.zip)

**Comment by codygeary** [comment]
Try updating to the latest version of the plugin.  I got rid of the -10V 'feature' since it's too annoying, now it spits out a root note if the string is muted. This way even if you don't patch up the muting you get nice sounding chords.

I can't open your patch fully since I don't have most of those modules installed... but taking a quick peek anyways, I think I know what you did. The outputs of the Plucks need to go into the Mute8 module, use the Mute outputs from the Strings to turn on and off the channels, then patch the outs of Mute8 to the mixer.

**Comment by codygeary** [comment]
Oh, yes also.
I put a few demo patches of Strings onto my Patchstorage that you can use to get started:
https://patchstorage.com/author/cody_geary/

**Comment by fractalgee** [comment]
OK, updating to latest fixed that one. Thanks. Now on to check your demo patches.
