### ISSUE TITLE
Collatz crashes when changing values

### ISSUE THREAD

**Issue by spacejoey86** [codygeary/CVfunk-Modules#5]
I am using the Collatz module in VCV rack.
When moving the knobs, or using the modulus CV, or the number CV (which seems to be multiplied by 100 and ignores the attenuator, not sure if this is intentional?), many combinations of number and modulus cause the module to crash.
For example any where both numbers are the same, or any where the modulus is one, or some other combinations like 15 mod 5.
The error experienced is: `Floating point exception (core dumped)`

**Comment by codygeary** [comment]
That's pretty serious, it doesn't do this for the ARM build, so can you please tell me what platform you are using.  I will try to make a fix for it ASAP!

**Comment by codygeary** [comment]
I just pushed out a bugfix for this. Can you please test it, the compiled plugin can be found on the right in the Nightly Builds box if you need.

What was happening is a divide by zero error when the Mod comes to zero. Apparently on my platform the NaN that results doesn't cause any errors or crashes and so I didn't notice the issue. I think I fixed all such references with zero-checking logic (but I'll need you to check that for me on your platform, since mine doesn't crash on such errors).

Also, yep I forgot to multiply by the attenuator there. I swear I tested that, but it's fixed now - thanks for spotting it!!

Finally, yes, the CV is supposed to be multiplied by 100x. Otherwise you'd only have 10 possible starting numbers, and there are technically infinite Collatz sequences possible.  I limited the range to the first 1000 numbers so that that resulting numbers wouldn't overflow the screen.

Thanks again for reporting this problem!

**Comment by spacejoey86** [comment]
Thanks for the quick reply and fix. I have tested this and it works perfectly.
Looking forward to trying out this module fully when I get a chance.
For reference I am using the lin-x64 build.
That makes sense about the CV multiplication.
Cheers.
